# Generated by Django 3.2.2 on 2022-01-11 12:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0002_user_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='favorite',
        ),
    ]
